/**
 * Issue #7 Wave 2 (F5) — minimal markdown renderer for the DetailModal's
 * notes field.
 *
 * Supports: **bold**, *italic*, `code`, [text](url), - lists, # headings,
 * paragraphs, hard line breaks. NO HTML pass-through (any literal `<` is
 * escaped). This is intentional — notes are user-authored prose, and a
 * permissive HTML allowlist would be a real security surface for a
 * synced-across-tabs field. If a user wants rich content they can ship a
 * link.
 *
 * Implementation is a single-pass tokenizer-ish state machine with
 * regex-based inline substitution. Not bundled with `marked` /
 * `markdown-it` because the supported feature set is tiny and we'd rather
 * not add ~30KB of runtime + a transitive dep tree for that.
 */

/**
 * HTML-escape a string. Used both on raw user text before any markdown
 * substitution and on URL strings before they land in href attributes.
 */
function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/**
 * Allowlist URL schemes for links. javascript:/data:/file: are rejected to
 * avoid XSS-via-markdown if notes are ever surfaced in a permissioned
 * context (Issue #8 etc.). Relative paths and #anchors are allowed since
 * they can't escalate beyond the host page.
 */
function safeUrl(raw: string): string {
  const url = raw.trim();
  if (url === "") return "#";
  // Allow anything that doesn't look like a scheme (relative + anchor)
  if (!/^[a-z][a-z0-9+.-]*:/i.test(url)) return url;
  // Allowlist schemes
  if (/^(https?|mailto):/i.test(url)) return url;
  return "#";
}

/**
 * Apply inline substitutions to a single line of already-html-escaped text.
 * Order matters: code first (so its contents aren't reprocessed), then
 * bold, then italic, then links.
 */
function renderInline(escaped: string): string {
  // `code` — single backtick, no nesting.
  let html = escaped.replace(/`([^`]+)`/g, "<code>$1</code>");
  // **bold** — non-greedy so `**a** **b**` doesn't merge.
  html = html.replace(/\*\*([^*\n]+)\*\*/g, "<strong>$1</strong>");
  // *italic* — non-greedy
  html = html.replace(/(^|[^*])\*([^*\n]+)\*(?!\*)/g, "$1<em>$2</em>");
  // [text](url)
  html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_m, text: string, url: string) => {
    const href = escapeHtml(safeUrl(url));
    return `<a href="${href}" target="_blank" rel="noopener noreferrer">${text}</a>`;
  });
  return html;
}

/**
 * Render markdown to a (sanitized) HTML string. Suitable for direct
 * insertion via `dangerouslySetInnerHTML` because every user-supplied byte
 * was either html-escaped at the start of processing or generated by one of
 * the structural transformations.
 *
 * Returns `""` for empty input so callers can branch on truthiness.
 */
export function renderMarkdown(source: string): string {
  if (!source) return "";

  // Escape ALL user input first; subsequent transformations only emit
  // trusted tags.
  const lines = source.split(/\r?\n/).map(escapeHtml);

  const out: string[] = [];
  let inList = false;
  let paragraphBuf: string[] = [];

  function flushParagraph() {
    if (paragraphBuf.length === 0) return;
    const joined = paragraphBuf.join("<br>");
    out.push(`<p>${renderInline(joined)}</p>`);
    paragraphBuf = [];
  }

  function closeList() {
    if (inList) {
      out.push("</ul>");
      inList = false;
    }
  }

  for (const line of lines) {
    const trimmed = line.trim();
    // Blank line — close the open paragraph / list.
    if (trimmed === "") {
      flushParagraph();
      closeList();
      continue;
    }
    // Heading — 1..6 leading #.
    const heading = /^(#{1,6})\s+(.+)$/.exec(trimmed);
    if (heading) {
      flushParagraph();
      closeList();
      const level = heading[1]!.length;
      out.push(`<h${level}>${renderInline(heading[2]!)}</h${level}>`);
      continue;
    }
    // Bullet — leading "- " or "* " (not bold).
    const bullet = /^[-*]\s+(.+)$/.exec(trimmed);
    if (bullet && !trimmed.startsWith("**")) {
      flushParagraph();
      if (!inList) {
        out.push("<ul>");
        inList = true;
      }
      out.push(`<li>${renderInline(bullet[1]!)}</li>`);
      continue;
    }
    // Plain text — accumulate as a paragraph.
    closeList();
    paragraphBuf.push(line);
  }
  flushParagraph();
  closeList();

  return out.join("\n");
}
