#!/usr/bin/env bash
# PrixmaViz Hostinger deploy script.
# Run on the VPS as root (sudo bash).
# Idempotent — safe to re-run for updates.
#
# Quick start (first run):
#   curl -fsSL https://raw.githubusercontent.com/MichaelDanCurtis/PrixmaViz/main/scripts/deploy-hostinger.sh | bash
#
# Subsequent runs (updates):
#   cd /srv/prixmaviz && bash scripts/deploy-hostinger.sh
#
# Cloudflare proxy (orange cloud):
#   If you front the VPS with Cloudflare's proxy, port 80 is unreachable from
#   Let's Encrypt and the default HTTP-01 challenge fails. This script will use
#   the DNS-01 challenge against Cloudflare's API instead — but only if you set
#   CF_API_TOKEN in /srv/prixmaviz/.env. See docs/deploy.md for details.

set -euo pipefail

DEPLOY_DIR="/srv/prixmaviz"
REPO_URL="https://github.com/MichaelDanCurtis/PrixmaViz.git"
BRANCH="main"
DOMAIN="prixmaviz.ailuxis.com"
COMPOSE_FILES=(-f docker-compose.yaml -f docker-compose.hostinger.yaml)

log() { echo "[deploy] $*"; }

# --- step 1: install Caddy if missing ---
if ! command -v caddy &> /dev/null; then
  log "installing Caddy..."
  apt-get update
  apt-get install -y debian-keyring debian-archive-keyring apt-transport-https curl gnupg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
    | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
    | tee /etc/apt/sources.list.d/caddy-stable.list
  apt-get update
  apt-get install -y caddy
fi

# --- step 2: clone or update repo ---
if [ ! -d "$DEPLOY_DIR/.git" ]; then
  log "cloning repo to $DEPLOY_DIR..."
  mkdir -p "$(dirname "$DEPLOY_DIR")"
  git clone --branch "$BRANCH" "$REPO_URL" "$DEPLOY_DIR"
else
  log "updating existing repo in $DEPLOY_DIR..."
  git -C "$DEPLOY_DIR" fetch origin
  git -C "$DEPLOY_DIR" reset --hard "origin/$BRANCH"
fi
cd "$DEPLOY_DIR"

# --- step 3: ensure .env exists ---
if [ ! -f .env ]; then
  log "creating .env from template..."
  cp .env.example .env

  # Production-sane defaults
  sed -i "s|^PRIXMAVIZ_PUBLIC_URL=.*|PRIXMAVIZ_PUBLIC_URL=https://$DOMAIN|" .env
  sed -i "s|^HOST_PORT=.*|HOST_PORT=127.0.0.1:5180|" .env

  # Strong Postgres password (hex, URL-safe by construction)
  PG_PASS="$(openssl rand -hex 24)"
  sed -i "s|^DATABASE_URL=.*|DATABASE_URL=postgres://prixmaviz:${PG_PASS}@postgres:5432/prixmaviz|" .env

  # Inject the matching password for the bundled Postgres container, plus
  # an empty Cloudflare API token placeholder. The token is REQUIRED if you
  # plan to front this host with Cloudflare's proxy (orange cloud); without
  # it, Caddy falls back to HTTP-01 which only works if port 80 reaches the
  # VPS directly (grey cloud / no Cloudflare).
  cat >> .env <<EOF

# Generated by deploy script; matches DATABASE_URL above.
POSTGRES_PASSWORD=${PG_PASS}

# Cloudflare API token for DNS-01 cert challenge. Required if Cloudflare's
# proxy ("orange cloud") is enabled for this domain — otherwise Let's Encrypt
# can't reach the VPS on port 80 and cert acquisition fails. Create at
# https://dash.cloudflare.com/profile/api-tokens with the "Edit zone DNS"
# template scoped to the parent zone. Leave empty to use HTTP-01 (grey cloud).
CF_API_TOKEN=
EOF
  chmod 600 .env

  log "generated /srv/prixmaviz/.env with a strong Postgres password."
  log ""
  log "NEXT STEPS:"
  log "  1. Edit /srv/prixmaviz/.env and set CF_API_TOKEN if you use Cloudflare's"
  log "     proxy (orange cloud). If you don't, leave it empty — Caddy will use"
  log "     HTTP-01 instead."
  log "  2. Re-run this script to build and start the stack:"
  log "       cd /srv/prixmaviz && bash scripts/deploy-hostinger.sh"
  exit 0
fi

# --- step 3b: load .env (safely) so subsequent steps see CF_API_TOKEN ---
# `set -a` exports everything sourced; we scope it tightly and turn it off
# right after. CF_API_TOKEN, if empty, just becomes an empty string — fine.
set -a
# shellcheck disable=SC1091
source .env
set +a

# Decide which challenge Caddy will use. Empty token = HTTP-01 fallback.
USE_DNS01="0"
if [ -n "${CF_API_TOKEN:-}" ]; then
  USE_DNS01="1"
  log "CF_API_TOKEN set — using Cloudflare DNS-01 challenge."
else
  log "CF_API_TOKEN empty — falling back to HTTP-01. This will FAIL if"
  log "Cloudflare's proxy (orange cloud) is on. Set CF_API_TOKEN in .env"
  log "and re-run to switch to DNS-01."
fi

# --- step 4: ensure caddy-dns/cloudflare module is present if we need it ---
# `caddy add-package` (Caddy 2.7+) downloads a custom build from caddyserver.com
# and atomically replaces the system binary. We then `apt-mark hold caddy` so
# apt upgrades don't revert it. To upgrade Caddy later:
#   sudo apt-mark unhold caddy && sudo apt-get install --only-upgrade caddy
#   sudo caddy add-package github.com/caddy-dns/cloudflare
#   sudo apt-mark hold caddy
if [ "$USE_DNS01" = "1" ]; then
  if ! caddy list-modules 2>/dev/null | grep -q "dns.providers.cloudflare"; then
    log "adding caddy-dns/cloudflare module (one-time, ~30s)..."
    caddy add-package github.com/caddy-dns/cloudflare
    apt-mark hold caddy
    log "apt-mark hold applied. To upgrade Caddy later: apt-mark unhold caddy."
  else
    log "caddy-dns/cloudflare already installed."
  fi
fi

# --- step 5: write Caddyfile site config ---
# We always overwrite the prixmaviz block so re-runs flip between DNS-01 and
# HTTP-01 cleanly when CF_API_TOKEN is added/removed. Other site blocks in
# /etc/caddy/Caddyfile (if any) are untouched because we manage a dedicated
# include file. Stock Caddy on Debian/Ubuntu imports /etc/caddy/Caddyfile.d/*
# via the trailing `import` in the default Caddyfile — but to avoid depending
# on that, we just replace the whole Caddyfile with our site block. If you
# host other sites on this VPS, manage them via additional includes.
CADDYFILE="/etc/caddy/Caddyfile"
mkdir -p /var/log/caddy

log "writing Caddyfile for $DOMAIN..."
if [ "$USE_DNS01" = "1" ]; then
  cat > "$CADDYFILE" <<EOF
# Managed by deploy-hostinger.sh. DNS-01 via Cloudflare.
# The literal {env.CF_API_TOKEN} is read by Caddy at runtime from systemd env.
$DOMAIN {
    tls {
        dns cloudflare {env.CF_API_TOKEN}
    }
    reverse_proxy 127.0.0.1:5180
    encode gzip zstd
    log {
        output file /var/log/caddy/prixmaviz.log
        format json
    }
}
EOF
else
  cat > "$CADDYFILE" <<EOF
# Managed by deploy-hostinger.sh. HTTP-01 (default).
# Will fail if Cloudflare's proxy fronts this domain — set CF_API_TOKEN to
# switch to DNS-01.
$DOMAIN {
    reverse_proxy 127.0.0.1:5180
    encode gzip zstd
    log {
        output file /var/log/caddy/prixmaviz.log
        format json
    }
}
EOF
fi

# --- step 5b: systemd drop-in to expose CF_API_TOKEN to caddy ---
# Caddy's `{env.CF_API_TOKEN}` placeholder reads from the systemd unit's
# environment, NOT from the Caddyfile environment. We write a drop-in unit
# file and chmod 600 it so the token isn't world-readable on disk.
DROPIN_DIR="/etc/systemd/system/caddy.service.d"
DROPIN_FILE="$DROPIN_DIR/cloudflare-token.conf"
if [ "$USE_DNS01" = "1" ]; then
  mkdir -p "$DROPIN_DIR"
  # Write to a temp file first, then move + chmod, so the token never appears
  # on disk world-readable (even for a moment).
  TMP_DROPIN="$(mktemp)"
  cat > "$TMP_DROPIN" <<EOF
[Service]
Environment="CF_API_TOKEN=${CF_API_TOKEN}"
EOF
  chmod 600 "$TMP_DROPIN"
  mv "$TMP_DROPIN" "$DROPIN_FILE"
  # Do NOT log the token. Just confirm presence.
  log "systemd drop-in written at $DROPIN_FILE (mode 600)."
  systemctl daemon-reload
elif [ -f "$DROPIN_FILE" ]; then
  log "removing stale cloudflare-token drop-in (CF_API_TOKEN now empty)..."
  rm -f "$DROPIN_FILE"
  systemctl daemon-reload
fi

# Restart (not just reload) since the env vars may have changed.
log "restarting caddy..."
systemctl restart caddy

# Surface any immediate cert errors so the user notices.
sleep 10
log "recent Caddy cert-related log entries:"
journalctl -u caddy --since "30 seconds ago" --no-pager 2>/dev/null \
  | grep -E "obtaining|certificate obtained|certificate obtained successfully|error|failed" \
  | tail -5 \
  || log "  (no obvious cert messages yet — may still be in progress)"

# --- step 6: build + start the stack ---
log "building prixmaviz image..."
docker compose "${COMPOSE_FILES[@]}" build prixmaviz

log "bringing the stack up..."
docker compose "${COMPOSE_FILES[@]}" up -d

# --- step 7: wait for local health ---
log "waiting for http://127.0.0.1:5180/api/health..."
for i in {1..60}; do
  if curl -fs http://127.0.0.1:5180/api/health > /dev/null; then
    log "container healthy after ${i}s."
    break
  fi
  sleep 1
done

# --- step 8: verify externally ---
# DNS-01 propagation + Cloudflare cache can take 60-90s on first issuance.
# Cloudflare's edge cert is always valid (Universal SSL), so no -k needed.
log "verifying https://$DOMAIN/api/health (allow up to 90s for cert + CF cache)..."
EXT_OK="0"
for i in {1..18}; do
  if curl -fs --max-time 5 "https://$DOMAIN/api/health" > /dev/null 2>&1; then
    log "OK https://$DOMAIN/api/health is alive (after ${i}x5s)."
    EXT_OK="1"
    break
  fi
  sleep 5
done

if [ "$EXT_OK" != "1" ]; then
  log "external check failed. Diagnostics:"
  log "  - DNS:        dig +short $DOMAIN  (Cloudflare IPs if orange cloud, VPS IP if grey)"
  log "  - Ports:      ss -tlnp | grep -E ':(80|443) '"
  log "  - Caddy:      systemctl status caddy && journalctl -u caddy -n 100"
  log "  - Cert:       journalctl -u caddy | grep -E 'cert|tls|challenge' | tail -20"
  log "  - App:        docker compose ${COMPOSE_FILES[*]} ps"
  log "  - CF mode:    SSL/TLS in Cloudflare dashboard must be 'Full (strict)'"
fi

log "done."
