#!/usr/bin/env bash
# PrixmaViz Hostinger deploy script.
# Run on the VPS as root (sudo bash).
# Idempotent — safe to re-run for updates.
#
# Quick start (first run):
#   curl -fsSL https://raw.githubusercontent.com/MichaelDanCurtis/PrixmaViz/main/scripts/deploy-hostinger.sh | bash
#
# Subsequent runs (updates):
#   cd /srv/prixmaviz && bash scripts/deploy-hostinger.sh

set -euo pipefail

DEPLOY_DIR="/srv/prixmaviz"
REPO_URL="https://github.com/MichaelDanCurtis/PrixmaViz.git"
BRANCH="main"
DOMAIN="prixmaviz.alexis.com"
COMPOSE_FILES=(-f docker-compose.yaml -f docker-compose.hostinger.yaml)

log() { echo "[deploy] $*"; }

# --- step 1: install Caddy if missing ---
if ! command -v caddy &> /dev/null; then
  log "installing Caddy..."
  apt-get update
  apt-get install -y debian-keyring debian-archive-keyring apt-transport-https curl gnupg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
    | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
    | tee /etc/apt/sources.list.d/caddy-stable.list
  apt-get update
  apt-get install -y caddy
fi

# --- step 2: clone or update repo ---
if [ ! -d "$DEPLOY_DIR/.git" ]; then
  log "cloning repo to $DEPLOY_DIR..."
  mkdir -p "$(dirname "$DEPLOY_DIR")"
  git clone --branch "$BRANCH" "$REPO_URL" "$DEPLOY_DIR"
else
  log "updating existing repo in $DEPLOY_DIR..."
  git -C "$DEPLOY_DIR" fetch origin
  git -C "$DEPLOY_DIR" reset --hard "origin/$BRANCH"
fi
cd "$DEPLOY_DIR"

# --- step 3: ensure .env exists ---
if [ ! -f .env ]; then
  log "creating .env from template..."
  cp .env.example .env

  # Production-sane defaults
  sed -i "s|^PRIXMAVIZ_PUBLIC_URL=.*|PRIXMAVIZ_PUBLIC_URL=https://$DOMAIN|" .env
  sed -i "s|^HOST_PORT=.*|HOST_PORT=127.0.0.1:5180|" .env

  # Strong Postgres password (hex, URL-safe by construction)
  PG_PASS="$(openssl rand -hex 24)"
  sed -i "s|^DATABASE_URL=.*|DATABASE_URL=postgres://prixmaviz:${PG_PASS}@postgres:5432/prixmaviz|" .env

  # Inject the matching password for the bundled Postgres container
  cat >> .env <<EOF

# Generated by deploy script; matches DATABASE_URL above.
POSTGRES_PASSWORD=${PG_PASS}
EOF
  chmod 600 .env

  log "generated /srv/prixmaviz/.env with a strong Postgres password."
  log ""
  log "NEXT STEPS:"
  log "  1. Review /srv/prixmaviz/.env (optional — defaults are sane)."
  log "  2. Re-run this script to build and start the stack:"
  log "       cd /srv/prixmaviz && bash scripts/deploy-hostinger.sh"
  exit 0
fi

# --- step 4: write Caddyfile site config if missing ---
CADDYFILE="/etc/caddy/Caddyfile"
mkdir -p /var/log/caddy
if ! grep -q "$DOMAIN" "$CADDYFILE" 2>/dev/null; then
  log "appending Caddy site config for $DOMAIN..."
  cat >> "$CADDYFILE" <<EOF

$DOMAIN {
    reverse_proxy 127.0.0.1:5180
    encode gzip zstd
    log {
        output file /var/log/caddy/prixmaviz.log
        format json
    }
}
EOF
  systemctl reload caddy || systemctl restart caddy
fi

# --- step 5: build + start the stack ---
log "building prixmaviz image..."
docker compose "${COMPOSE_FILES[@]}" build prixmaviz

log "bringing the stack up..."
docker compose "${COMPOSE_FILES[@]}" up -d

# --- step 6: wait for local health ---
log "waiting for http://127.0.0.1:5180/api/health..."
for i in {1..60}; do
  if curl -fs http://127.0.0.1:5180/api/health > /dev/null; then
    log "container healthy after ${i}s."
    break
  fi
  sleep 1
done

# --- step 7: verify externally ---
log "verifying https://$DOMAIN/api/health (first run may take ~30s while Caddy fetches a cert)..."
sleep 5
if curl -fsk --max-time 30 "https://$DOMAIN/api/health" > /dev/null; then
  log "OK https://$DOMAIN/api/health is alive."
else
  log "external check failed. Diagnostics:"
  log "  - DNS:        dig +short $DOMAIN  (should return this host's public IP)"
  log "  - Ports:      ss -tlnp | grep -E ':(80|443) '"
  log "  - Caddy:      systemctl status caddy && journalctl -u caddy -n 50"
  log "  - App:        docker compose ${COMPOSE_FILES[*]} ps"
fi

log "done."
